### ISSUE TITLE
Comcutter fails to make backup of video file

### ISSUE THREAD

**Issue by ceejayemm** [bljohnsondev/comcutter#3]
I have been using JellyFin for a while (currently v10.10.5) and decided to give comskip a try to remove ads from recorded TV shows.  I came across your project and used your docker-compose file as the basis for setting up my own instance.  I also used the default config.yml file.  Both modified for my own locations etc

```
config.yml

api:
  apikey: "*******" # replace this with your own generated key
  log_dir: "/data/logs"
  log_level: "debug"
  library_dir: "/library"
  port: 8080

comskip:
  comskip_cmd: "/usr/local/bin/comskip"
  comskip_ini: "/data/config/comskip.ini"
  cmd: "/usr/local/bin/comcut"
  keep_edl: true
  timeout: 300
  size_percentage: 0.7

postprocess:
  # cmd: "/data/scripts/postcall.sh"
```
```
PostProcessing.sh

filepath="$@"

# example file - '/data/media/dvr/Family Guy/Season 22/Family Guy S22E05 Old World Harm.ts'
stripped=`echo "$filepath" | cut -c 12-`

curl -X POST \
  http://cmdock-w2:8080/comskip \
  -H 'Content-Type: application/json' \
  -d "{\"api\": \"*******", \"file\": \"${stripped}\"}"
```

After a recording the call is made via PostProcessing.sh to the comcutter container process and I can see the process starting in the comcutter.log file:

```
01-28-2025 05:37:52 PM - INFO    : Serving on http://0.0.0.0:8080
01-28-2025 05:46:00 PM - INFO    : processing file: /library/tvshows/This Week Back Then/This Week Back Then 2022-02-14.ts
01-28-2025 05:46:00 PM - DEBUG   : backing up file:
source      : /library/tvshows/This Week Back Then/This Week Back Then 2022-02-14.ts
destination : /library/tvshows/This Week Back Then/This Week Back Then 2022-02-14.ts.bak
01-28-2025 08:05:00 PM - INFO    : processing file: /library/tvshows/Emmerdale/Season 2025/Emmerdale S2025E24.ts
01-28-2025 08:05:00 PM - DEBUG   : backing up file:
source      : /library/tvshows/Emmerdale/Season 2025/Emmerdale S2025E24.ts
destination : /library/tvshows/Emmerdale/Season 2025/Emmerdale S2025E24.ts.bak
```
 You can see that the copy process is started but then nothing else happens.  If I check the container log file I can see that the copy fails due to a permissions error:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/comlistener/comskipper.py", line 24, in run
    self.run_command(filepath)
  File "/comlistener/comskipper.py", line 120, in run_command
    self.backup_file(filepath)
  File "/comlistener/comskipper.py", line 62, in backup_file
    shutil.copy(filepath, backuppath)
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/library/tvshows/Emmerdale/Season 2025/Emmerdale S2025E24.ts.bak'

```

Starting a console session inside the container DOES allow me to copy these files to the same locations so it would seem the general permissions are OK. I presume the console session, running inside the container, runs with the same permissions as the normal process ?

The comcutter docker-compose file I have used is:

```
version: "2.1"
services:
  comcutter:
    image: bljohnsondev/comcutter
    container_name: comcutter
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 8080:8080
    volumes:
      - /dockerlocal/comcutter/data:/data
      - /dockerlocal/jellyfin/data/local:/library
    restart: unless-stopped
```

and the jellyfin docker-compose is:

```
version: "3.0"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /dockerlocal/jellyfin/config:/config
      - /dockerlocal/jellyfin/cache:/cache
      - /dockerlocal/jellyfin/data:/data
      - /nfs/recordings/TVShows:/data/tvshows
      - /nfs/recordings/Films:/data/movies
      - /nfs/images/scans:/data/Scans
      - /nfs/images/photos/Albums:/data/Pictures
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    network_mode: 'host'
```

So you can see the paths to the recording library location are basically the same.  I am at a loss as to how to solve this problem. 

Can you help please, many thanks.

Chris
